version: '3'

services:
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    restart: always
    image: mariadb:5.5.64
    env_file:
      - '.env'
    ports:
      - "3306:3306"

  # nodeserver:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-nodeserver
  #   command: ["/usr/local/bin/npm", "run", "dev",]
  #   volumes:
  #     - ./nodeserver/:/usr/src/app/
  #   ports:
  #     - "50080:50080"
  #   depends_on:
  #     - redis
  #     - db

  # transferworker:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-transferworker
  #   command: ["/usr/local/bin/npm", "run", "dev",]
  #   volumes:
  #     - ./transferworker/:/usr/src/app/
  #   depends_on:
  #     - nodeserver

  monitorworker:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile-monitorworker
    command: ["/usr/local/bin/npm", "run", "dev",]
    volumes:
      - ./monitorworker/:/usr/src/app/
    # depends_on:
    #   # - nodeserver
