version: '3'

services:
  redis:
    restart: always
    image: "redis:alpine"

  nodeserver:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile-nodeserver
    command: ["pm2-runtime", "server.js"]
    volumes:
      - ./nodeserver/:/usr/src/app/
    env_file:
      - '.env'
    ports:
      - "50080:50080"
    depends_on:
      - redis

  arena:
    restart: always
    image: mixmaxhq/arena:latest
    volumes:
      - ./arena.json:/opt/arena/src/server/config/index.json
    env_file:
      - '.env'
    ports:
      - "4567:4567"
    depends_on:
      - redis

  transferworker:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile-transferworker
    command: ["pm2-runtime", "app.js"]
    volumes:
      - ./transferworker/:/usr/src/app/
    env_file:
      - '.env'
    depends_on:
      - nodeserver

  monitorworker:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile-monitorworker
    command: ["pm2-runtime", "app.js"]
    volumes:
      - ./monitorworker/:/usr/src/app/
    env_file:
      - '.env'
    depends_on:
      - nodeserver
